export const beerColors = {
  other: [
    /brett/,
    /chile beer/,
    /chilli/,
    /cider/,
    /energy drink/,
    /flanders/,
    /freeze-distilled/,
    /fruit beer/,
    /lambic/,
    /mead/,
    /non-alcoholic - sour/,
    /radler/,
    /rtd /,
    /soda/,
    /sour/,
    /wild/,
  ],
  dark: [
    /adambier/,
    /altbier/,
    /barleywine/,
    /black/,
    /bock - doppelbock/,
    /bock - hell/,
    /bock - single/,
    /brown/,
    /dark/,
    /dubbel/,
    /dunkelweizen/,
    /eisbock/,
    /kellerbier/,
    /old ale/,
    /porter/,
    /pumpkin/,
    /quadrupel/,
    /rauchbier/,
    /red ale/,
    /rye beer/,
    /rye wine/,
    /schwarzbier/,
    /scottish/,
    /smoked/,
    /spiced/,
    /stout/,
    /wee heavy/,
    /winter/,
  ],
  light: [
    /bitter/,
    /blonde/,
    /bock - weizenbock/,
    /california common/,
    /champagne/,
    /cream ale/,
    /de garde/,
    /farmhouse/,
    /festbier/,
    /ginger/,
    /gluten-free/,
    /golden/,
    /graff/,
    /grape ale/,
    /grisette/,
    /grodziskie/,
    /gruit/,
    /honey/,
    /ipa/,
    /kristallweizen/,
    /kölsch/,
    /lager/,
    /lichtenhainer/,
    /malt liquor/,
    /mild ale/,
    /märzen/,
    /non-alcoholic/,
    /pale/,
    /patersbier/,
    /pils/,
    /saison/,
    /sparkling/,
    /specialty grain/,
    /strong ale/,
    /table/,
    /tripel/,
    /weizen/,
    /wheat/,
    /witbier/,
  ],
}
